<a href="https://colab.research.google.com/github/ragcode7/ML-SEM5/blob/main/ML_LAB2ANS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **19CSE305: MACHINE LEARNING LAB 2**

PYTHON BASICS : EXERCISES

ROLL NUMBER: CB.EN.U4CSE19046

In [ ]:
QUESTIONS
PYTHON BASIC EXCERSISE

1)Get two positive integers start and end from the user and write a Python program to print all Prime numbers in that Interval.
2) Given a list of strings( Entered by the user), write program to get a percentage share of each word in the strings list.
percentage := (Occurrence of a word / Total words) * 100
3)Check if  given number is Fibonacci number or not. Given an integer ‘n’( Entered by the user), write a Python function that returns true if n  is Fibonacci number else return false.
4)Write a program to check if all digits of a number divide it. Given a number n( Entered by the user), find whether all digits of n divide it or not.
5)Get a given array as input from the user and split it from a specified position, and move the first part of array add to the end.
example:
Input : {1, 2, 3, 4, 5}, k = 3
Output :{4,5,1,2,3}


NUMPY BASIC EXCERSISE

1) Create a 2D array of shape 4x5 that contains random decimal numbers between 3 and 10.
2) Create a randomly created 1D array and Convert it to a 2D array with 2 rows.
3) Given a NumPy array of temperature values, convert the values of Fahrenheit degrees into Centigrade degrees. 
4) Write a NumPy program to count the number of dimensions, number of elements and number of bytes for each element in a given array.
5) Write a NumPy program to extract third and fourth elements of the second and third rows from a given (3x4) array.



SOLUTIONS

PYTHON BASICS 

In [6]:
#1. Get two positive integers start and end from the user and write a Python program to print all Prime numbers in that Interval.

#input of the lower and upper bound
lower= int(input("Enter the starting number : "))
upper =int(input("Enter the ending number : "))

print("Prime numbers between", lower, "and", upper, "are:")

for num in range(lower, upper + 1):
   # all prime numbers are greater than 1
   if num > 1:
       for i in range(2, num):
           if (num % i) == 0:
               break
       else:
           print(num)

Enter the starting number : 2
Enter the ending number : 10
Prime numbers between 2 and 10 are:
2
3
5
7


In [27]:
#2. Given a list of strings( Entered by the user), write program to get a percentage share of each word in the strings list.
#percentage := (Occurrence of a word / Total words) * 100
from collections import Counter
  

               
test_list= ["hello this is the first line",
            "hello this is the seconnf line"]
joined = " ".join(ele for ele in test_list)
  

mappd = Counter(joined.split())
  
total_val = sum(mappd.values())
  

res = {key: val / total_val for key,
       val in mappd.items()}

print("Percentage share of each word : " + str(res))


Percentage share of each word : {'hello': 0.16666666666666666, 'this': 0.16666666666666666, 'is': 0.16666666666666666, 'the': 0.16666666666666666, 'first': 0.08333333333333333, 'line': 0.16666666666666666, 'seconnf': 0.08333333333333333}


In [10]:
#3. Check if  given number is Fibonacci number or not. Given an integer ‘n’( Entered by the user), write a Python function that returns true if n  is Fibonacci number else return false.

import math
num = int(input("Enter an integer number: "))

def checkPerfectSquare(n):
    sqrt = int(math.sqrt(n))
    if pow(sqrt, 2) == n:
        return True
    else:
        return False
def isFibonacciNumber(n):
    res1 = 5 * n * n + 4
    res2 = 5 * n * n - 4
    if checkPerfectSquare(res1) or checkPerfectSquare(res2):
        return True
    return False
if isFibonacciNumber(num):
    print ("True")
else:
    print ("False")


Enter an integer number: 13
True


In [11]:
#4. Write a program to check if all digits of a number divide it. Given a number n( Entered by the user), find whether all digits of n divide it or not.
n = int(input("Enter an integer number: "))
def divisibilityCheck(n,dig):
  return(dig!=0 and n%dig==0)
def digDivideAll(n):
  tempo=n
  while(tempo>0):
    dig=tempo%10
    if((divisibilityCheck(n,dig))==False):
      return False
    tempo=tempo//10
  return True

if(digDivideAll(n)):
  print("Yes,all digits of the number will divide it ")
else:
  print("No,all digits of the number will not divide it")

Enter an integer number: 128
Yes,all digits of the number will divide it 


In [18]:
#5. Get a given array as input from the user and split it from a specified position, and move the first part of array add to the end.
#example:
#Input : {1, 2, 3, 4, 5}, k = 3
#Output :{4,5,1,2,3}

def arraySplit(arr, n, k):
    for i in range(0, k):
        x = arr[0]
        for j in range(0, n-1):
            arr[j] = arr[j + 1]
         
        arr[n-1] = x
         
 
arr = [1, 2, 3, 4, 5]
n = len(arr)
position = 3
 
arraySplit(arr, n, position)
 
for i in range(0, n):
    print(arr[i], end = ' ')


4 5 1 2 3 

NUMPY BASICS

In [29]:
#1. Create a 2D array of shape 4x5 that contains random decimal numbers between 3 and 10.
import numpy as np
random_matrix_array = np.random.randint(3,11,size=(4,5))
print(random_matrix_array)

[[ 6  7  4  3  3]
 [ 9  4  4  6 10]
 [ 5  4  8  9  7]
 [ 5  9  9  5  9]]


In [15]:
#2. Create a randomly created 1D array and Convert it to a 2D array with 2 rows.
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [16]:
#3.Given a NumPy array of temperature values, convert the values of Fahrenheit degrees into Centigrade degrees. 
import numpy as np
fahrenheitvalues = [0, 12, 45.21, 34, 99.91]
Fa = np.array(fahrenheitvalues)
print("Values in Centigrade degrees:") 
print(5*Fa/9 - 5*32/9)

Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [17]:
#4. Write a NumPy program to count the number of dimensions, number of elements and number of bytes for each element in a given array.
import numpy as np    
print("\nOriginal array:")
x = np.array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
print(x)
print("\nNumber of dimensions:")
print(x.ndim)
print("Number of elements:")
print(x.size)
print("Number of bytes for each element in the said array:")
print(x.itemsize) 



Original array:
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]

Number of dimensions:
2
Number of elements:
24
Number of bytes for each element in the said array:
8


In [20]:
#5. Write a NumPy program to extract third and fourth elements of the second and third rows from a given (3x4) array.
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Third and Fourth elements of the second and third rows")
print(arra_data[0:2, 2:4])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and Fourth elements of the second and third rows
[[2 3]
 [6 7]]
